### PR TITLE
Core path update

### PR DESCRIPTION
**Pull request by pepelsbey**
[@shower/core](https://www.npmjs.com/package/@shower/core) is now released as v3.0.0 stable, so I’m currently moving the rest of the packages to the `@shower` organization. To publish the `@shower/shower` package I need to update the cli with the new core path first.

Would you mind checking my changes and releasing the new cli version? :)

### CODE REVIEW

**Comment by nikolay-govorov** [comment]
Hi. Thank you for your contribution.

I'm at work right now, but I'll check and release the update today.

**Comment by pepelsbey** [comment]
> If you don't want to get into the code, I can finish it myself tonight

Huh, too late. Done :)

**Comment by nikolay-govorov** [comment]
Oh, and the filename too, please :)

https://github.com/shower/cli/blob/7b9b04be0a663437d4666e911b1b403af5cb7e26/core/lib/presentation.js#L37

**Comment by pepelsbey** [comment]
Done.

It kinda makes you understand that it’s a bit too much hard-coded ;)

**Comment by nikolay-govorov** [comment]
Yes, I agree that it is worth making this dependency more flexible.

**Comment by nikolay-govorov** [comment]
I published version 0.3.0 in npm, with your PR.

**Pull request merged**
